=== igneus/ordodo/xml/ordodo.dtd
<!-- DTD for the ordodo configuration file -->

<!ELEMENT ordodo (meta?,head?,temporale?,calendar?)>
<!ATTLIST ordodo locale CDATA "en">

<!ELEMENT meta (title?,description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT head (title?)>

<!ELEMENT temporale (extension*,option*)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT option EMPTY>
<!ATTLIST option type (transfer_to_sunday) #REQUIRED>
<!ATTLIST option feast CDATA #REQUIRED>
<!ATTLIST option apply (always|optional|never) #REQUIRED>

<!ELEMENT calendar (artefact*,calendar*)>
<!ATTLIST calendar title CDATA #REQUIRED>
<!ELEMENT artefact EMPTY>
<!ATTLIST artefact type (packaged|file) #REQUIRED>
<!ATTLIST artefact ref CDATA #REQUIRED>

=== igneus/ordodo/examples/general_roman.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE ordodo SYSTEM "../xml/ordodo.dtd">

<ordodo locale="en">
  <meta>
    <title>General Roman Calendar</title>
    <description>
      The easiest case: generating an ordo for a single calendar.
    </description>
  </meta>

  <temporale>
    <!--
        Transfer of Epiphany, Ascension and Corpus Christi
        is optional.
    -->
    <option type="transfer_to_sunday" feast="Epiphany" apply="optional" />
    <option type="transfer_to_sunday" feast="Ascension" apply="optional" />
    <option type="transfer_to_sunday" feast="Corpus Christi" apply="optional" />
  </temporale>

  <!--
      Structure of sanctorale data.
  -->
  <calendar title="General Roman Calendar">
    <artefact type="packaged" ref="universal-en" />
  </calendar>
</ordodo>

=== igneus/ordodo/examples/czech_republic.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE ordodo SYSTEM "../xml/ordodo.dtd">

<ordodo locale="cs">
  <!--
      Metainformation for your own use
  -->
  <meta>
    <title>Liturgický kalendář pro české a moravské diecéze</title>
    <description>
      Configuration of an ordo for Roman Catholic dioceses
      of Czech Republic.
    </description>
  </meta>

  <!--
      Titles used by ordodo
  -->
  <head>
    <title>Liturgický kalendář pro české a moravské diecéze</title>
  </head>

  <temporale>
    <!--
        Additional movable feasts not included
        in the General Roman Calendar.

        Currently no other feast than "Christ Eternal Priest"
        is supported. If you need one, open an issue.
    -->
    <extension>Christ Eternal Priest</extension>

    <!--
        Optional transfer of solemnities on Sunday.

        Only the three solemnities of Epiphany, Ascension
        and Corpus Christi can be transferred this way.

        apply="optional" generates variants for scenarios both
        with and without the transfer;
        apply="always" generates only variant for scenario
        with the transfer;
        apply="never" (default - leaving the option out has the
        same effect) generates only variant without the transfer
    -->
    <option type="transfer_to_sunday" feast="Epiphany" apply="optional" />
    <option type="transfer_to_sunday" feast="Ascension" apply="optional" />
    <option type="transfer_to_sunday" feast="Corpus Christi" apply="optional" />
  </temporale>

  <!--
      Structure of sanctorale data.

      The church organisation in Czech Republic is relatively
      simple: there are only two provinces, each having
      a handful of dioceses. Since the liturgical reform of Vatican II
      a great part of the liturgical calendar is common to all of them.

      There is no nesting limit imposed by ordodo, you can
      use as many levels as necessary.
  -->

  <!--
      Each calendar consists of a title,
      zero or more "artefacts" (files with calendar data,
      in the format used by calendarium-romanum gem)
      and zero or more child calendars.

      If there is more than one artefact in a single calendar,
      artefacts are loaded in the given order, which means
      that in case of conflict the last one always wins.
      Similarly child calendars always win over parents.
  -->
  <calendar title="české a moravské diecéze">
    <artefact type="packaged" ref="czech-cs" />

    <!-- province Bohemia and it's dioceses -->
    <calendar title="česká církevní provincie">
      <artefact type="packaged" ref="czech-cechy-cs" />

      <calendar title="arcidiecéze pražská">
        <artefact type="packaged" ref="czech-praha-cs" />
      </calendar>
      <calendar title="litoměřická diecéze">
        <artefact type="packaged" ref="czech-litomerice-cs" />
      </calendar>
      <calendar title="královéhradecká diecéze">
        <artefact type="packaged" ref="czech-hradec-cs" />
      </calendar>
      <calendar title="českobudějovická diecéze">
        <artefact type="packaged" ref="czech-budejovice-cs" />
      </calendar>
      <calendar title="plzeňská diecéze">
        <artefact type="packaged" ref="czech-plzen-cs" />
      </calendar>
    </calendar>

    <!-- province Moravia and it's dioceses -->
    <calendar title="moravská církevní provincie">
      <artefact type="packaged" ref="czech-morava-cs" />

      <calendar title="arcidiecéze olomoucká">
        <artefact type="packaged" ref="czech-olomouc-cs" />
      </calendar>
      <calendar title="brněnská diecéze">
        <artefact type="packaged" ref="czech-brno-cs" />
      </calendar>
      <calendar title="diecéze ostravsko-opavská">
        <artefact type="packaged" ref="czech-ostrava-cs" />
      </calendar>
    </calendar>
  </calendar>
</ordodo>
